// Deepam replica — static site generator
// Reads data.js (via a Node-shimmed globals) and emits index, audio, books,
// about, deity/*.html and books/*.html.

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const DATA_FRAME = fs.readFileSync(path.join(ROOT, 'data.js'), 'utf8');
const D = eval(DATA_FRAME.replace('const DeepamData =', '(').replace(/;\s*$/, ')'));

const esc = (s) => String(s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));

function rel(rootDepth, file) {
  return rootDepth === 0 ? file : '../'.repeat(rootDepth) + file;
}

function head(title, desc, depth, extra) {
  return `<!DOCTYPE html>
<html lang="en" data-text-size="base">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>${esc(title)}</title>
<meta name="description" content="${esc(desc)}"/>
<link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
<link href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400;9..144,500;9..144,600&family=Karla:wght@400;500;600;700&family=Noto+Serif+Telugu:wght@400;500;600;700&display=swap" rel="stylesheet"/>
<link rel="stylesheet" href="${rel(depth, 'styles.css')}?v=37"/>
${extra || ''}
</head>
<body>`;
}

const PAGES = {
  index: ['index.html', 'Saptarushi — Telugu Bhakti Books & Audio', 'A calm Telugu devotional library: deity-wise bhajans, chants and books that play and read right inside the site.'],
  audio: ['audio.html', 'Audio — Telugu bhajans & chants | Saptarushi', 'Listen to Telugu bhajans, chants and aartis for every deity, streamed in the browser.'],
  books: ['books.html', 'Books — Telugu devotional reading | Saptarushi', 'Telugu devotional books and guides you can read comfortably right in the browser.'],
  about: ['about.html', 'About Saptarushi — a calm Telugu bhakti library', 'Why Saptarushi exists: Telugu devotional audio and books in one gentle, easy-to-read place.'],
  panchangam: ['panchangam.html', 'Panchangam — Telugu daily almanac | Saptarushi', 'Vara, Tithi, Nakshatra, Yoga and Karana for any date and town, with muhurtas, choghadiya and festivals — computed for any date and town, never hard-coded.'],
};
const DEITY_PAGES = {
  venkateswara: 'Venkateswara', shiva: 'Shiva', rama: 'Rama', krishna: 'Krishna', ganesha: 'Ganesha',
  hanuman: 'Hanuman', durga: 'Durga / Devi', lakshmi: 'Lakshmi', saibaba: 'Saibaba',
  ayyappa: 'Ayyappa', subrahmanya: 'Subrahmanya', navagraha: 'Navagraha',
};
const TEMPLES = JSON.parse(fs.readFileSync(path.join(ROOT, 'temples.json'), 'utf8'));
const TEMPLE_CATS = TEMPLES.categories;
const TEMPLE_CONTENT = JSON.parse(fs.readFileSync(path.join(ROOT, 'temples-content.json'), 'utf8'));
const BOOK_PAGES = {
  'venkateswara-mahatyam': 'వేంకటేశ్వర మహాత్మ్యం',
  'shiva-daily': 'శివ ఆరాధన',
  'rama-katha': 'రామ కథ',
  'krishna-gita-notes': 'గీతా పఠన సూచనలు',
  'ganesha-prayers': 'వినాయక ప్రార్థనలు',
  'hanuman-readings': 'శనివార పఠనాలు',
};

/* =========================================================
   STOTRA NIDHI integration
   Lyrics for ~25 well-known stotras, pulled from
   stotranidhi.com, become Books (long-form Telugu) and
   Audio tiles (recording served from their channel).
   ========================================================= */
const STOTRAS = JSON.parse(fs.readFileSync(path.join(ROOT, 'stotras.json'), 'utf8')).items;
const snAudio = [];
const snBooks = [];
STOTRAS.forEach((s) => {
  const slug = 'sn-' + s.slug;
  const title = s.en || s.te;
  const a = {
    slug, deity: s.deity, te: s.te, en: title, duration: '—', tag: 'Stotra',
    localPath: '', src: s.src, text: 'Telugu text and chant from Stotra Nidhi (stotranidhi.com) — the full lyrics are in the Books section.',
  };
  snAudio.push(a);
  D.audio.push(a);
  const paras = s.paras.filter(Boolean);
  const chapters = [];
  if (paras.length <= 32) { chapters.push({ title: 'పారాయణ పాఠం', paras }); }
  else {
    for (let i = 0; i < paras.length; i += 32) {
      chapters.push({ title: 'భాగం – ' + (chapters.length + 1), paras: paras.slice(i, i + 32) });
    }
  }
  const b = {
    slug, deity: s.deity, te: s.te, en: title, meta: 'Stotra Nidhi · పారాయణ పాఠం · శ్లో. తా.',
    chapters, source: s.src,
  };
  snBooks.push(b);
  D.books.push(b);
  BOOK_PAGES[slug] = s.te;
});
/* Runtime copy so app.js can find the Stotra Nidhi tracks (clicks, filters). */
fs.writeFileSync(path.join(ROOT, 'stotras-runtime.js'),
  '// generated by build.js — Stotra Nidhi audio/books for the runtime\n;window.__SN__=' +
  JSON.stringify({ audio: snAudio, books: snBooks }) + ';\n');
console.log('Stotra Nidhi: added ' + snAudio.length + ' audio + ' + snBooks.length + ' books; wrote stotras-runtime.js.');

function header(rootDepth, active) {
  const R = rel(rootDepth, '');
  const home = rel(rootDepth, 'index.html');
  const audio = rel(rootDepth, 'audio.html');
  const books = rel(rootDepth, 'books.html');
  const temples = rel(rootDepth, 'temples.html');
  const panchang = rel(rootDepth, 'panchangam.html');
  const about = rel(rootDepth, 'about.html');
  const cls = (p) => (active === p ? ' class="active"' : '');
  return `  <header class="site-header">
    <div class="header-inner">
      <a class="brand" href="${home}">
        <span class="brand-mark">${logoMark()}</span>
        <span class="leading-none">
          <span class="brand-name">${D.brand.name}</span>
          <span class="brand-tag">${D.brand.tagline}</span>
        </span>
      </a>
      <nav class="main-nav">
        <a href="${audio}"${cls('audio')}>Audio</a>
        <a href="${books}"${cls('books')}>Books</a>
        <a href="${temples}"${cls('temples')}>Temples</a>
        <a href="${panchang}"${cls('panchang')}>Panchang</a>
        <a href="${about}"${cls('about')}>About</a>
        <a href="${R}admin.html" class="nav-admin">Admin</a>
      </nav>
      <div class="header-right">
        <span class="textsize-label">Text size</span>
        <div class="textsize-group" role="group" aria-label="Text size">
          <button class="textsize-btn" data-size="base" aria-label="Text size A">A</button>
          <button class="textsize-btn" data-size="large" aria-label="Text size A+">A+</button>
          <button class="textsize-btn" data-size="xlarge" aria-label="Text size A++">A++</button>
        </div>
        <button class="menu-trigger" id="menuTrigger" aria-label="Open menu">☰</button>
      </div>
    </div>
  </header>
  <nav class="mobile-nav" id="mobileNav">
    <a href="${home}"${cls('index')}>Home</a>
    <a href="${audio}"${cls('audio')}>Audio</a>
    <a href="${books}"${cls('books')}>Books</a>
    <a href="${temples}"${cls('temples')}>Temples</a>
    <a href="${panchang}"${cls('panchang')}>Panchang</a>
    <a href="${about}"${cls('about')}>About</a>
    <a href="${R}admin.html" class="nav-admin">Admin</a>
  </nav>`;
}

function backBar(rootDepth, label) {
  return `<nav class="back-bar" aria-label="Back"><a class="back-btn" href="${rel(rootDepth, 'index.html')}">← ${label}</a></nav>`;
}

function deityRail(rootDepth, currentSlug) {
  const out = ['<div class="deity-rail">'];
  D.deities.forEach(d => {
    const active = d.slug === currentSlug ? ' active' : '';
    const img = deityImgAsset(d.slug, rootDepth);
    out.push(`<a class="deity-pill${active}" title="${d.label}" href="${rel(rootDepth, 'deity/' + d.slug + '.html')}">
      ${img ? `<img class="pill-icon" src="${img}" alt="${d.label}" loading="lazy"/>` : `<span class="pill-symbol" aria-hidden="true">${esc(d.symbol)}</span>`}
      <span class="pill-label">${d.label}</span>
    </a>`);
  });
  out.push('</div>');
  return out.join('\n');
}

function trackCard(rootDepth, t) {
  const comingSoon = t.comingSoon ? ' is-coming-soon' : '';
  const comingAttr = t.comingSoon ? ' data-coming-soon="true"' : '';
  const img = deityImgAsset(t.deity, rootDepth);
  return `<button type="button" class="track-card${comingSoon}" data-slug="${t.slug}"${comingAttr}>
    <div class="track-art">
      ${img ? `<img src="${img}" alt="" loading="lazy"/>` : ''}
      <span class="track-play-btn" aria-hidden="true">▶</span>
    </div>
    <div class="track-row">
      <p class="track-te truncate" lang="te">${t.te}</p>
      <span class="track-dur">${t.duration}</span>
    </div>
    <p class="track-meta truncate">${esc(t.en)} · ${esc(t.tag)}</p>
  </button>`;
}

function bookCard(rootDepth, b) {
  const img = b.imageUrl || b.coverUrl || deityImgAsset(b.deity, rootDepth);
  const badge = b.isNew ? `<span class="book-new-badge">NEW</span>` : '';
  return `<a class="book-card" href="${rel(rootDepth, 'books/' + b.slug + '.html')}">
    ${badge}
    ${img ? `<img class="book-cover-img" src="${img}" alt="${esc(b.en)}" loading="lazy"/>` : ''}
    <div class="min-w-0 flex-1">
      <p class="book-te" lang="te">${b.te}</p>
      <p class="book-en">${esc(b.en)}</p>
      <p class="book-meta">${esc(b.meta)}</p>
    </div>
  </a>`;
}

/* ---------- Temples helpers ---------- */
function templeBadge(t) { return TEMPLE_CATS[t.category] || t.category; }

const DEITY_EXT = { krishna: '.png' };
function deityImgAsset(slug, depth) {
  const f = 'assets/deities/' + slug + (DEITY_EXT[slug] || '.jpg');
  return fs.existsSync(path.join(ROOT, f)) ? rel(depth, f) : '';
}
function templeCardImg(cat, id) {
  const base = 'assets/temples/' + cat + '/' + id + '-';
  if (fs.existsSync(path.join(ROOT, base + 'temple.jpg'))) return base + 'temple.jpg';
  if (fs.existsSync(path.join(ROOT, base + 'deity.jpg'))) return base + 'deity.jpg';
  return '';
}
function templeCardImgRel(cat, id, depth) {
  const u = templeCardImg(cat, id);
  return u ? rel(depth, u) : '';
}

function templeJs(t) {
  return {
    id: t.id, category: t.category, categoryLabel: templeBadge(t), name: t.name, temple: t.temple,
    deity: t.deity, city: t.city, state: t.state, location: t.location, story: t.story,
    significance: t.significance, bodyPart: t.bodyPart || '', element: t.element || '',
    coords: t.coordinates,
    cardImg: templeCardImg(t.category, t.id),
  };
}
function templeCard(rootDepth, t, mode) {
  const img = templeCardImgRel(t.category, t.id, rootDepth);
  const imgHtml = img ? `<img class="temple-img" src="${img}" alt="${esc(t.name)}" loading="lazy"/>` : '';
  const content = `
    ${imgHtml}
    <div class="temple-content">
      <span class="temple-badge">${esc(templeBadge(t))}</span>
      <h2 class="temple-name">${esc(t.name)}</h2>
      <div class="temple-deity">${esc(t.deity)}</div>
      <div class="temple-loc">${esc(t.location)}</div>
      <div class="temple-read"></div>
    </div>`;
  if (mode === 'button') {
    return `<article class="temple-card">${content.replace('<div class="temple-read"></div>',
      '<div class="temple-read"><button type="button" onclick="openTemple(\'' + t.id + '\')">Explore Temple</button></div>')}</article>`;
  }
  return `<article class="temple-card">${content.replace('<div class="temple-read"></div>',
    '<div class="temple-read"><a href="' + rel(rootDepth, 'temples/' + t.id + '.html') + '" class="temple-link-btn">Explore Temple</a></div>')}</article>`;
}

function fabAndShell(rootDepth, extraScripts) {
  // resources loaded after body content; rootDepth used for script/data base
  const base = rootDepth === 0 ? '' : '../'.repeat(rootDepth);
  return `  <!-- Ask Rushi chat -->
  <div class="fab-zone">
    <div class="chat-panel" id="chatPanel" aria-hidden="true">
      <div class="chat-head">
        <span class="chat-avatar">${logoMark(34)}</span>
        <div class="min-w-0 flex-1">
          <div class="chat-head-strong">Ask Rushi</div>
          <span class="chat-head-sub"><i></i> online · plays from library</span>
        </div>
        <button class="chat-min" id="chatMin" aria-label="Close chat">–</button>
      </div>
      <div class="chat-msgs" id="chatMsgs"></div>
      <div class="chat-sugg" id="chatSugg"></div>
      <form class="chat-form" id="chatForm">
        <input id="chatInput" placeholder="Ask: play Suprabhatam…" autocomplete="off"/>
        <button class="chat-send" aria-label="Send">➤</button>
      </form>
    </div>
    <button id="askBtn" class="askbtn" aria-expanded="false"><span class="ask-icon">✦</span>Ask Rushi</button>
  </div>

  <!-- in-page player -->
  <div class="player-bar" id="player" aria-hidden="true">
    <span class="mp-eq"><span></span><span></span><span></span><span></span><span></span></span>
    <div class="mp-info">
      <div class="mp-te" id="mpTe"></div>
      <div class="mp-en" id="mpEn"></div>
    </div>
    <button class="mp-action" id="mpToggle" aria-label="Play or pause">⏸</button>
    <button class="mp-action" id="mpStop" aria-label="Stop">⏹</button>
  </div>

  <script src="${base}data.js"></script>
  <script src="${base}stotras-runtime.js"></script>
  <script src="${base}lang-editor.js"></script>
  <script src="${base}media-player.js"></script>
  <script src="${base}text-editor.js"></script>
  <script src="${base}app.js" data-base="${base}"></script>
  ${extraScripts || ''}
  <footer class="app-footer">
    <span class="footer-note">Saptarushi · తెలుగు భక్తి — listen &amp; read in the browser</span>
    <span class="footer-links">
      <a href="${base}about.html">About</a>
      <a href="${base}admin.html">Admin</a>
    </span>
  </footer>
</body>
</html>`;
}

/* ---------- Brand logo: meditating sage with the seven-star (Saptarishi) halo ---------- */
function logoMark(sz) {
  sz = sz || 40;
  return `<svg class="brand-logo" viewBox="0 0 48 48" width="${sz}" height="${sz}" aria-hidden="true" focusable="false">
  <circle cx="24" cy="24" r="23.5" fill="#2e1418"/>
  <circle cx="24" cy="24" r="22.25" fill="rgba(242, 166, 58, 0.07)"/>
  <circle cx="24" cy="24" r="23.5" fill="none" stroke="rgba(242,166,58,0.4)" stroke-width="1"/>
  <g fill="#f2a63a">
    <circle cx="12" cy="13" r="1.15"/><circle cx="16.9" cy="8.5" r="1.15"/>
    <circle cx="21.6" cy="6.6" r="1.15"/><circle cx="24" cy="6.2" r="1.15"/>
    <circle cx="26.4" cy="6.6" r="1.15"/><circle cx="31.1" cy="8.5" r="1.15"/>
    <circle cx="36" cy="13" r="1.15"/>
  </g>
  <g fill="#f2a63a">
    <circle cx="24" cy="14" r="3"/>
    <path d="M21.7 16.3c.7 1.2 1.9 1.7 2.3 1.7s1.6-.5 2.3-1.7"/>
    <path d="M20.3 18.5c-2.6 2.4-3.9 5.9-3.4 9.7.3 2.3.2 3.6.2 3.6h12.2h.2s-.1-1.3.2-3.6c.5-3.8-.8-7.3-3.4-9.7-2.1.9-5.1.9-7.2 0z"/>
    <path d="M18.8 32.4c2.3 1.9 6 1.9 8.3 0"/>
  </g>
</svg>`;
}

/* ---------------- TEMPLES ---------------- */

function templesPage() {
  const T = TEMPLES.items;
  const counts = {};
  T.forEach(t => { counts[t.category] = (counts[t.category] || 0) + 1; });
  const states = [...new Set(T.map(t => t.state))].sort();
  const json = JSON.stringify(T.map(templeJs));

  const leafCSS = `<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"/>`;
  const leafJS = `  <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>`;
  const templeJS = `  <script>
  (function () {
    const TEMPLES = ${json};
    const CATINFO = ${JSON.stringify(TEMPLE_CATS)};
    const CAT_ORDER = ['shakti', 'jyotirlinga', 'pancharama', 'chardham', 'panchabhoota'];
    const CATS = Object.keys(TEMPLES);
    let currentCategory = 'all';

    /* state dropdown */
    const stateSelect = document.getElementById('tstate');
    [...new Set(TEMPLES.map(t => t.state))].sort().forEach(s => {
      const o = document.createElement('option');
      o.value = s; o.textContent = s; stateSelect.appendChild(o);
    });

    function setCategory(cat, btn) {
      currentCategory = cat;
      document.querySelectorAll('.filter-chip[data-cat]').forEach(b => b.classList.toggle('active', b === btn));
      renderTemples();
    }

    function renderTemples() {
      const grid = document.getElementById('templeGrid');
      const q = (document.getElementById('tsearch').value || '').toLowerCase().trim();
      const st = stateSelect.value;
      const grouped = currentCategory === 'all' && !q && st === 'all';
      if (grouped) {
        grid.innerHTML = CAT_ORDER.map(cat => {
          const list = TEMPLES.filter(t => t.category === cat);
          if (!list.length) return '';
          const emoji = { shakti: '🙏', jyotirlinga: '🕉', pancharama: '🛕', chardham: '🚩', panchabhoota: '🌍' }[cat] || '🛕';
          return '<div class="temple-group">'
            + '<div class="temple-group-head"><span class="temple-group-emoji">' + emoji + '</span>'
            + '<h2 class="temple-group-title">' + CATINFO[cat] + '</h2>'
            + '<span class="temple-group-count">' + list.length + ' shrines</span></div>'
            + '<div class="temple-grid">' + list.map(cardHtml).join('') + '</div>'
            + '</div>';
        }).join('');
        return;
      }
      const list = TEMPLES.filter(t => {
        if (currentCategory !== 'all' && t.category !== currentCategory) return false;
        if (st !== 'all' && t.state !== st) return false;
        if (!q) return true;
        return (t.name + ' ' + t.temple + ' ' + t.deity + ' ' + t.city + ' ' + t.state + ' ' + (t.element || '')).toLowerCase().includes(q);
      });
      grid.innerHTML = list.length
        ? list.map(cardHtml).join('')
        : \`<div class="temple-empty"><h2>No temples found</h2><p>Try another temple, deity, city or state.</p></div>\`;
    }

    function cardHtml(t) {
      return \`<article class="temple-card">
        \${t.cardImg ? \`<img class="temple-img" src="\${t.cardImg}" alt="\${t.name}" loading="lazy"/>\` : ''}
        <div class="temple-content">
          <span class="temple-badge">\${t.categoryLabel}</span>
          <h2 class="temple-name">\${t.name}</h2>
          <div class="temple-deity">🙏 \${t.deity}</div>
          <div class="temple-loc">📍 \${t.location}</div>
          <div class="temple-read"><button type="button" onclick="openTemple('\${t.id}')">Explore Temple</button></div>
        </div>
      </article>\`;
    }

    /* modal */
    const modal = document.getElementById('templeModal');
    function openTemple(id) {
      const t = TEMPLES.find(x => x.id === id);
      if (!t) return;
      const parts = [];
      parts.push('<div class="temple-modal-body">');
      parts.push('<span class="temple-badge">' + t.categoryLabel + '</span>');
      if (t.category === 'panchabhoota') parts.push('<span class="temple-badge" style="margin-left:6px">' + t.element + '</span>');
      parts.push('<h2>' + t.name + '</h2>');
      parts.push('<div class="temple-modal-sub">' + t.temple + ' · ' + t.deity + '</div>');
      if (t.bodyPart) parts.push('<div class="temple-modal-sub">' + 'Traditions associate this Peetha with: ' + t.bodyPart + '</div>');
      parts.push('<h3>🕉 Story</h3><p>' + t.story + '</p>');
      parts.push('<h3>✨ Significance</h3><p>' + t.significance + '</p>');
      parts.push('<h3>📍 Location</h3><p>' + t.location + '</p>');
      parts.push('<p style="margin-top:0.9rem"><a class="temple-link-btn" style="display:inline-block;width:auto" href="temples/' + t.id + '.html">Open full temple page ⇗</a></p>');
      parts.push('</div>');
      document.getElementById('templeModalContent').innerHTML = parts.join('');
      modal.classList.add('active');
      document.body.style.overflow = 'hidden';
    }
    window.openTemple = openTemple;
    function closeTemple() {
      modal.classList.remove('active');
      document.body.style.overflow = '';
    }
    window.closeTemple = closeTemple;
    modal.querySelector('.temple-modal-close').addEventListener('click', closeTemple);
    modal.addEventListener('click', e => { if (e.target === modal) closeTemple(); });
    document.addEventListener('keydown', e => { if (e.key === 'Escape') closeTemple(); });

    document.getElementById('tsearch').addEventListener('input', renderTemples);
    stateSelect.addEventListener('change', renderTemples);
    document.querySelectorAll('.filter-chip[data-cat]').forEach(b =>
      b.addEventListener('click', () => setCategory(b.dataset.cat, b)));

    /* leaflet map */
    try {
      if (window.L) {
        const map = L.map('templeMap').setView([21.9, 78.5], 5);
        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
          attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
          maxZoom: 18,
        }).addTo(map);
        TEMPLES.forEach(t => {
          if (!t.coords) return;
          L.marker([t.coords.lat, t.coords.lng]).addTo(map).bindPopup(
            '<strong>' + t.name + '</strong><br>' + t.city + (t.state ? ', ' + t.state : '') +
            '<br><a class="tp" href="temples/' + t.id + '.html">Temple page &rarr;</a>');
        });
      } else {
        document.getElementById('templeMap').innerHTML = '<div class="map-note">Map loads when you are online (OpenStreetMap). The temple list below works fully offline.</div>';
      }
    } catch (err) {
      document.getElementById('templeMap').innerHTML = '<div class="map-note">Map unavailable here (OpenStreetMap tiles need an internet connection).</div>';
    }

    renderTemples();
  })();
  </script>`;

  const parts = [];
  parts.push(head('Temples of India — Sacred shrines | Saptarushi', 'Explore the Shakti Peethas, Jyotirlingas, Pancharamas, Char Dham and Pancha Bhoota temples of India, with search, filters and a map.', 0, leafCSS));
  parts.push(`<div class="bg-parch text-ink min-h-screen">`);
  parts.push(header(0, 'temples'));
  parts.push(backBar(0, 'Home'));
  parts.push(`<main>
  <section class="temple-hero">
    <p class="hero-eyebrow" style="color:var(--marigold)">Sacred India · సనాతన భారతం</p>
    <h1>Temples of India</h1>
    <p>Seats of Devi, twelve Jyotirlingas, the Pancharamas, the four Char Dham and the Pancha Bhoota temples — search, filter, and explore with a map.</p>
    <div class="temple-hero-stats">
      <span class="temple-hero-stat">${counts.shakti || 0} Shakti Peethas</span>
      <span class="temple-hero-stat">${counts.jyotirlinga || 0} Jyotirlingas</span>
      <span class="temple-hero-stat">${counts.pancharama || 0} Pancharamas</span>
      <span class="temple-hero-stat">${counts.chardham || 0} Char Dham</span>
      <span class="temple-hero-stat">${counts.panchabhoota || 0} Pancha Bhoota</span>
    </div>
  </section>
  <section class="section-page">
    <div class="filter-row temple-filter-row">
      <button class="filter-chip active" data-cat="all">All</button>
      ${Object.keys(TEMPLE_CATS).map(c => `<button class="filter-chip" data-cat="${c}">${TEMPLE_CATS[c]}</button>`).join('\n')}
    </div>
    <div class="temple-controls">
      <input id="tsearch" type="search" placeholder="Search temple, deity, city, state…" autocomplete="off"/>
      <select id="tstate"><option value="all">All States</option></select>
    </div>
    <div class="temple-map-wrap">
      <div id="templeMap" class="temple-map"></div>
    </div>
    <div class="temple-grid" id="templeGrid" style="margin-top:2rem"></div>
  </section>
  </main>
  <div class="temple-modal" id="templeModal" aria-hidden="true">
    <div class="temple-modal-box">
      <button class="temple-modal-close" aria-label="Close temple">×</button>
      <div id="templeModalContent"></div>
    </div>
  </div>`);
  parts.push(fabAndShell(0, leafJS + templeJS));
  parts.push(`</div>`);
  return parts.join('\n');
}

function templePage(slug) {
  const t = TEMPLES.items.find(x => x.id === slug);
  const source = TEMPLE_CONTENT[t.id] || null;
  const headings = {
    en: ['Sthala Puranam', 'Explanation', 'Why the temple is revered'],
    te: ['స్థల పురాణం', 'వివరణ', 'పూజింపబడటానికి కారణం'],
  };
  function languageBlock(lang) {
    const c = source ? source[lang] : null;
    if (!c) return '';
    const [h1, h2, h3] = headings[lang];
    const langAttr = lang === 'te' ? ' lang="te"' : '';
    return `<h2 class="reading-h"${langAttr}>${h1}</h2>
        <p class="reading-p"${langAttr}>${esc(c.sthalapuram)}</p>
        <h2 class="reading-h"${langAttr}>${h2}</h2>
        <p class="reading-p"${langAttr}>${esc(c.explanation)}</p>
        <h2 class="reading-h"${langAttr}>${h3}</h2>
        <p class="reading-p"${langAttr}>${esc(c.reverence)}</p>`;
  }
  const toggle = `<div class="lang-switch" role="group" aria-label="Content language">
      <button type="button" class="lang-btn active" data-lang="en" aria-pressed="true">English</button>
      <button type="button" class="lang-btn" data-lang="te" aria-pressed="false">తెలుగు</button>
    </div>`;
  const toggleJs = `<script>
  (function () {
    var btns = Array.prototype.slice.call(document.querySelectorAll('.lang-btn'));
    var bodies = Array.prototype.slice.call(document.querySelectorAll('.temple-lang'));
    var saved = 'en';
    try { saved = localStorage.getItem('saptarushi-lang') || 'en'; } catch (e) {}
    function apply(lang) {
      var l = lang === 'te' ? 'te' : 'en';
      try { localStorage.setItem('saptarushi-lang', l); } catch (e) {}
      btns.forEach(function (b) {
        var on = b.getAttribute('data-lang') === l;
        b.classList.toggle('active', on); b.setAttribute('aria-pressed', on ? 'true' : 'false');
      });
      bodies.forEach(function (b) { b.style.display = b.getAttribute('data-lang') === l ? '' : 'none'; });
    }
    btns.forEach(function (b) { b.addEventListener('click', function () { apply(b.getAttribute('data-lang')); }); });
    apply(saved);
  })();
  </script>`;
  const heroRel = templeCardImgRel(t.category, t.id, 1);
  const deityRel = (() => {
    const f = 'assets/temples/' + t.category + '/' + t.id + '-deity.jpg';
    return fs.existsSync(path.join(ROOT, f)) ? rel(1, f) : '';
  })();
  const asideFig = heroRel ? `<figure class="temple-photo">
    <img class="temple-photo-img" src="${heroRel}" alt="${esc(t.name)}" loading="lazy"/>
  </figure>` : '';
  const deityFig = deityRel ? `<figure class="temple-deity-fig">
    <img class="temple-deity-img" src="${deityRel}" alt="${esc(t.deity)} — ${esc(t.name)}"/>
  </figure>` : '';
  const parts = [];
  parts.push(head(t.name + ' — Sacred Temples of India | Saptarushi', t.temple + ' — ' + t.deity + ' at ' + t.location + '. Sthala Puranam, story and significance, in the Saptarushi temple index.', 1));
  parts.push(`<div class="bg-parch text-ink min-h-screen">`);
  parts.push(header(1, 'temples'));
  parts.push(`<main>`);
  parts.push(`<section class="book-top">
    <a class="back-link" href="../temples.html">← All temples</a>
    <div class="book-layout">
      <aside class="book-aside">
        ${asideFig}
        <h1 class="book-h1">${esc(t.name)}</h1>
        <p class="book-te-title">${esc(t.temple)}</p>
        <p class="book-meta-line">${esc(t.deity)} · ${esc(templeBadge(t))}${t.element ? ' · ' + esc(t.element) : ''}</p>
        ${t.bodyPart ? `<p class="book-meta-line">Traditions associate this Peetha with: ${esc(t.bodyPart)}</p>` : ''}
        <p class="book-meta-line">📍 ${esc(t.location)}</p>
        ${t.coordinates ? `<p class="book-meta-line">🗺 ${t.coordinates.lat.toFixed(3)}, ${t.coordinates.lng.toFixed(3)}</p>` : ''}
        ${t.coordinates ? `<p style="margin-top:1rem"><a class="temple-link-btn" style="display:inline-block;width:auto" target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(t.location)}">Open in Google Maps ⇗</a></p>` : ''}
        <p class="book-meta-line" style="margin-top:1rem;font-size:0.85rem"><a class="bn-source" href="../temples.html">Saptarushi temple index</a></p>
      </aside>
      <article class="reading-column">
        ${deityFig}
        ${toggle}
        <div class="temple-lang" data-lang="en">${languageBlock('en')}</div>
        <div class="temple-lang" data-lang="te" style="display:none">${languageBlock('te')}</div>
        <h2 class="reading-h">🕉 Story</h2>
        <p class="reading-p">${esc(t.story)}</p>
        <br/>
        <h2 class="reading-h">✨ Significance</h2>
        <p class="reading-p">${esc(t.significance)}</p>
      </article>
    </div>
  </section>`);
  parts.push(`</main>`);
  parts.push(fabAndShell(1, toggleJs));
  parts.push(`</div>`);
  return parts.join('\n');
}

/* ---------------- PANCHANGAM ---------------- */

/* The regime list for the Panchangam town dropdown is generated from the
   same panchang-places.js the client imports, so the drop-down and the
   computation can never disagree. */
const _PANC_SRC = fs.readFileSync(path.join(ROOT, 'panchang-places.js'), 'utf8')
  .replace(/\/\*[\s\S]*?\*\//g, '')
  .replace(/\/\/[^\n]*/g, '')
  .replace(/export const /g, '');
const _panc = { PLACES: null };
eval(_PANC_SRC + '\n; _panc.PLACES = PLACES;');
const PANC_PLACES = _panc.PLACES;

function placesSelect() {
  const groups = {};
  for (const p of PANC_PLACES) { (groups[p.co] || (groups[p.co] = [])).push(p); }
  const coOrder = ['India', ...Object.keys(groups).filter(c => c !== 'India').sort()];
  const selected = (p) => (p.co === 'India' && p.n === 'Bengaluru') ? ' selected' : '';
  const opts = coOrder.map(co => {
    const cities = groups[co].map(p =>
      `        <option value="${esc(co + '|' + p.n)}"${selected(p)}>${esc(p.n)}${p.st && p.st !== co ? ' — ' + esc(p.st) : ''}</option>`).join('\n');
    return `      <optgroup label="${esc(co)}">
${cities}
      </optgroup>`;
  }).join('\n');
  return `      <select id="panchPlace" class="panch-field-select" title="Choose a city">
        <option value="">Custom / manual coordinates…</option>
${opts}
      </select>`;
}

function panchangPage() {
  const parts = [];
  parts.push(head(PAGES.panchangam[1], PAGES.panchangam[2], 0));
  parts.push(`<div class="bg-parch text-ink min-h-screen">`);
  parts.push(header(0, 'panchang'));
  parts.push(backBar(0, 'Home'));
  parts.push(`<main>
  <section class="temple-hero panch-hero">
    <p class="hero-eyebrow" style="color:var(--marigold)">పంచాంగం · Daily Almanac</p>
    <h1>Today's Panchangam</h1>
    <p>The five limbs of the day — Vara, Tithi, Nakshatra, Yoga, Karana — with muhurtas, choghadiya and festivals. Computed for your place and date; nothing is hard-coded.</p>

    <div class="panch-controls">
      <label class="panch-field">
        <span class="panch-field-k">Date</span>
        <input type="date" id="panchDate"/>
      </label>
      <label class="panch-field">
        <span class="panch-field-k">Place</span>
        ${placesSelect()}
      </label>
      <label class="panch-field panch-field-sm">
        <span class="panch-field-k">Lat</span>
        <input id="panchLat" inputmode="decimal" placeholder="12.9716"/>
      </label>
      <label class="panch-field panch-field-sm">
        <span class="panch-field-k">Lng</span>
        <input id="panchLng" inputmode="decimal" placeholder="77.5946"/>
      </label>
      <button type="button" class="btn btn-outline" id="panchToday">Today</button>
      <button type="button" class="btn btn-primary" id="panchLocate">Use my location</button>
    </div>
    <p class="panch-status" id="panchStatus"></p>
  </section>

  <section class="section-page" id="results">
    <article class="panch-card panch-day">
      <div id="panchBig"></div>
      <div class="panch-day-mini">
        <span><b>Nakshatra</b> <em id="panchNak">—</em></span>
        <span><b>Masa</b> <em id="panchMasa">—</em></span>
        <span><b>Sun</b> <em id="panchSun">—</em></span>
      </div>
    </article>

    <div class="section-title-row" style="margin-top:2.25rem">
      <h2 class="section-title">Pancha Aṅga</h2>
      <span class="section-count">the five limbs of the Tithi</span>
    </div>
    <div class="anga-grid" id="angaGrid"></div>

    <div class="panch-cols">
      <div class="panch-col">
        <div class="section-title-row">
          <h2 class="section-title">Calendar</h2>
        </div>
        <div class="cal-box" id="calRows"></div>
      </div>
      <div class="panch-col">
        <div class="section-title-row">
          <h2 class="section-title">Festivals</h2>
        </div>
        <ul class="fest-list" id="festList"></ul>
      </div>
    </div>

    <div class="section-title-row" style="margin-top:2.25rem">
      <h2 class="section-title">Timings & Muhurtas</h2>
      <span class="section-count" id="panchSub"></span>
    </div>
    <div class="time-box" id="timeRows"></div>
    <div class="eclipse-panel" id="eclipseBox" hidden></div>

    <div class="section-title-row" style="margin-top:2.25rem">
      <h2 class="section-title">Choghadiya</h2>
      <span class="section-count">day & night auspicious hours</span>
    </div>
    <div class="chog-box">
      <div class="chog-group"><span class="chog-label">Day</span><div class="chog-chips" id="chogDay"></div></div>
      <div class="chog-group"><span class="chog-label">Night</span><div class="chog-chips" id="chogNight"></div></div>
    </div>

    <div class="section-title-row" style="margin-top:2.25rem">
      <h2 class="section-title">Saṅkalpam</h2>
      <span class="section-count">సంకల్పం · traditional Andhra chant</span>
    </div>
    <article class="panch-card sankalpam">
      <p class="sankalpam-text" id="sankalpamText" lang="te"></p>
      <button type="button" class="btn btn-outline" id="panchCopy" style="margin-top:1rem">Copy</button>
    </article>

  </section>
  </main>`);
  parts.push(fabAndShell(0, `<script type="module" src="panchang-app.js"></script>`));
  parts.push(`</div>`);
  return parts.join('\n');
}

/* ---------------- PAGE BUILDER ---------------- */

function homePage() {
  const parts = [];
  parts.push(head(PAGES.index[1], PAGES.index[2], 0));
  parts.push(`<div class="bg-parch text-ink min-h-screen">`);
  parts.push(header(0, ''));
  parts.push(`<main>`);
  // hero
  const heroImg = fs.existsSync(path.join(ROOT, 'assets/deity-venkateswara-BnOIfnAn.jpg'))
    ? 'assets/deity-venkateswara-BnOIfnAn.jpg' : '';
  parts.push(`<section class="hero-page">
    <div class="hero-flex">
      <div class="min-w-0 flex-1">
        <p class="hero-eyebrow">Telugu Bhakti · ${D.brand.tagline}</p>
        <h1 class="hero-title">A quiet place to listen and read.</h1>
        <p class="hero-desc">Bhajans, chants and devotional books for every deity — gathered in one calm, easy-on-the-eyes place. Everything plays and reads right here; nothing to download.</p>
        <div class="hero-actions">
          <a class="btn btn-primary" href="audio.html">Listen</a>
          <a class="btn btn-outline" href="books.html">Read</a>
        </div>
      </div>
      ${heroImg ? `<img class="hero-img hero-img-hero" src="${heroImg}" alt="Venkateswara"/>` : ''}
    </div>
  </section>`);
  // quick saṅkalpam card (populated by sankalpam-quick.js)
  parts.push(`<section class="section-page" style="padding-top:0">
    <article class="sankalpam-quick" id="sankalpamQuick">
      <div class="sankalpam-quick-head">
        <p class="hero-eyebrow" style="color:#f8d9a8">సంకల్పం · Daily</p>
        <h2 class="section-title" style="color:var(--parch)">Today's Saṅkalpam</h2>
        <div class="sankalpam-quick-meta" id="sankalpamQMeta">Computed for Bengaluru · computing…</div>
      </div>
      <p class="sankalpam-text" id="sankalpamQText" lang="te">బెంగుళూరుకి ఈరోజు సంకల్పం లెక్కిస్తున్నాం…</p>
      <div class="sankalpam-quick-foot">
        <a class="btn btn-outline" href="panchangam.html">Open full Panchangam page →</a>
        <span class="sankalpam-quick-note">full vara–tithi–nakshatra–muhurta for any date and town</span>
      </div>
    </article>
  </section>`);
  // deity rail section
  parts.push(`<section class="section-page">
    <div class="section-title-row">
      <h2 class="section-title">Choose your deity</h2>
      <span class="section-count">${D.deities.length} sections</span>
    </div>
    ${deityRail(0, null)}
  </section>`);
  // temples preview
  const featuredTemples = ['shakti', 'jyotirlinga', 'pancharama', 'chardham']
    .map(c => TEMPLES.items.find(t => t.category === c)).filter(Boolean);
  parts.push(`<section class="section-page">
    <div class="section-title-row">
      <h2 class="section-title">Temples of India</h2>
      <a class="see-all" href="temples.html">All ${TEMPLES.items.length} temples</a>
    </div>
    <div class="temple-grid" style="margin-top:1.25rem">${featuredTemples.map(t => templeCard(0, t, 'link')).join('\n')}</div>
  </section>`);
  // panchang preview
  parts.push(`<section class="section-page">
    <div class="section-title-row">
      <h2 class="section-title">Today's Panchangam</h2>
      <a class="see-all" href="panchangam.html">Open the almanac</a>
    </div>
    <p class="panch-teaser">The five aṅgas of the day and the auspicious hours — Tithi, Nakshatra, Yoga, Karana, Rahu Kaalam, Abhijit, Choghadiya — computed for any date and town from real astronomy, not copied from a fixed list.</p>
    <div style="margin-top:1.25rem"><a class="btn btn-primary" href="panchangam.html">Today's Panchangam →</a></div>
  </section>`);
  // audio preview
  const homeAudio = D.audio.slice(0, 4);
  parts.push(`<section class="section-page">
    <div class="section-title-row">
      <h2 class="section-title">Audio</h2>
      <a class="see-all" href="audio.html">All recordings</a>
    </div>
    <div class="grid-cards" id="homeAudioGrid">${homeAudio.map(t => trackCard(0, t)).join('\n')}</div>
  </section>`);
  // books preview
  const homeBooks = D.books.slice(0, 4);
  parts.push(`<section class="section-page">
    <div class="section-title-row">
      <h2 class="section-title">Books</h2>
      <a class="see-all" href="books.html">All books</a>
    </div>
    <div class="grid-books">${homeBooks.map(b => bookCard(0, b)).join('\n')}</div>
  </section>`);
  parts.push(`</main>`);
  parts.push(fabAndShell(0, `<script type="module" src="sankalpam-quick.js"></script>`));
  parts.push(`</div>`);
  return parts.join('\n');
}

function audioPage() {
  const parts = [];
  parts.push(head(PAGES.audio[1], PAGES.audio[2], 0));
  parts.push(`<div class="bg-parch text-ink min-h-screen">`);
  parts.push(header(0, 'audio'));
  parts.push(backBar(0, 'Home'));
  parts.push(`<main>
  <section class="section-page py-top">
    <div class="page-head">
      <h1>Audio</h1>
      <p>Everything here plays inside the site. Tap a tile and it keeps playing while you browse.</p>
    </div>
    <div class="filter-row">
      <button class="filter-chip active" data-filter="all">All</button>
      ${D.deities.map(d => `<button class="filter-chip" data-filter="${d.slug}">${d.label}</button>`).join('\n')}
    </div>
    <div class="grid-cards" id="audioGrid">${D.audio.map(t => trackCard(0, t)).join('\n')}</div>
  </section>
  </main>`);
  parts.push(fabAndShell(0));
  parts.push(`</div>`);
  return parts.join('\n');
}

function booksPage() {
  const parts = [];
  parts.push(head(PAGES.books[1], PAGES.books[2], 0));
  parts.push(`<div class="bg-parch text-ink min-h-screen">`);
  parts.push(header(0, 'books'));
  parts.push(backBar(0, 'Home'));
  parts.push(`<main>
  <section class="section-page py-top">
    <div class="page-head">
      <h1>Books</h1>
      <p>Open any book and read it here. Use the “Text size” buttons at the top right if you'd like bigger words.</p>
    </div>
    <div class="grid-books" style="margin-top:1.5rem">${D.books.map(b => bookCard(0, b)).join('\n')}</div>
  </section>
  </main>`);
  parts.push(fabAndShell(0));
  parts.push(`</div>`);
  return parts.join('\n');
}

function aboutPage() {
  const parts = [];
  parts.push(head(PAGES.about[1], PAGES.about[2], 0));
  parts.push(`<div class="bg-parch text-ink min-h-screen">`);
  parts.push(header(0, 'about'));
  parts.push(backBar(0, 'Home'));
  parts.push(`<main>
  <section class="section-page py-top">
    <div class="page-head">
      <h1>About Saptarushi</h1>
    </div>
    <div class="about-copy" style="margin-top:1.5rem">
      <p>Saptarushi gathers Telugu devotional listening and reading in one quiet place. Everything plays and opens inside the site, so nothing has to be downloaded.</p>
      <p>The colours here are deliberately warm and low-glare, the text is large, and the lines are widely spaced — so long reading and listening sessions stay comfortable. Use the “Text size” buttons at the top right to make everything bigger.</p>
    </div>
    <div class="about-note">
      <p>This is a faithful replica of the Saptarushi design — same layout, palette, fonts and content, rebuilt as a clean static site you can host anywhere.</p>
    </div>
  </section>
  </main>`);
  parts.push(fabAndShell(0));
  parts.push(`</div>`);
  return parts.join('\n');
}

function deityPage(slug) {
  const d = deityBySlug(slug);
  const aud = D.audio.filter(a => a.deity === slug);
  const bks = D.books.filter(b => b.deity === slug);
  const img = deityImgAsset(d.slug, 1);
  const parts = [];
  parts.push(head(`${d.label} — Telugu bhakti | Saptarushi`, d.desc + ' Listen to ' + d.label + ' bhajans and read ' + d.label + ' books in the browser.', 1));
  parts.push(`<div class="bg-parch text-ink min-h-screen">`);
  parts.push(header(1, ''));
  parts.push(backBar(1, 'Home'));
  parts.push(`<main>`);
  parts.push(`<section class="section-page">
    <div class="section-title-row"><h2 class="section-title">Choose your deity</h2><span class="section-count">${D.deities.length} sections</span></div>
    ${deityRail(1, slug)}
  </section>`);
  parts.push(`<section class="section-page">
    <div class="hero-flex" style="gap:1.5rem;margin-bottom:2rem">
      <div class="min-w-0 flex-1">
        <p class="hero-eyebrow">Deity</p>
        <h1 class="hero-title" style="max-width:none">${d.label}</h1>
        <p class="font-telugu text-xl" style="color:var(--ink-80);margin-top:0.25rem" lang="te">${d.te}</p>
        <p class="hero-desc">${d.desc}</p>
        <div class="flex" style="gap:2rem;margin-top:1.25rem;font-size:1rem">
          <span><strong class="font-display" style="font-size:1.25rem">${bks.length}</strong><span style="margin-left:0.375rem;color:var(--ink-70)">books</span></span>
          <span><strong class="font-display" style="font-size:1.25rem">${aud.length}</strong><span style="margin-left:0.375rem;color:var(--ink-70)">audio</span></span>
        </div>
      </div>
      ${img ? `<img class="hero-img deity-hero-img" src="${img}" alt="${d.label}"/>` : ''}
    </div>
    <div class="tabs">
      <button class="tab${bks.length ? '' : ''}" data-tab="books" aria-pressed="false">Books</button>
      <button class="tab active" data-tab="audio" aria-pressed="true">Audio</button>
      <span class="tab-note">Plays in-page · no downloads</span>
    </div>
    <div id="panelAudio">${aud.length ? `<div class="grid-cards">${aud.map(t => trackCard(1, t)).join('\n')}</div>` : '<p style="color:var(--ink-70)">No audio for this deity yet.</p>'}</div>
    <div id="panelBooks" style="display:none">${bks.length ? `<div class="grid-books">${bks.map(b => bookCard(1, b)).join('\n')}</div>` : '<p style="color:var(--ink-70)">No books for this deity yet.</p>'}</div>
  </section>`);
  parts.push(`</main>`);
  parts.push(fabAndShell(1));
  parts.push(`</div>`);
  return parts.join('\n');
}

function bookPage(slug) {
  const b = bookBySlug(slug);
  const d = deityBySlug(b.deity);
  const cover = b.imageUrl || b.coverUrl || deityImgAsset(b.deity, 1);
  const parts = [];
  parts.push(head(`${b.en} | Saptarushi`, b.en + ' — read ' + b.te + ' in a calm, large-text reader.', 1));
  parts.push(`<div class="bg-parch text-ink min-h-screen">`);
  parts.push(header(1, 'books'));
  parts.push(`<main>`);
  parts.push(`<section class="book-top">
    <a class="back-link" href="../books.html">← All books</a>
    <div class="book-layout">
      <aside class="book-aside">
        ${cover ? `<figure class="book-cover-fig"><img class="book-cover-img" style="width:100%;height:auto;aspect-ratio:1/1" src="${cover}" alt="${esc(b.en)}" loading="lazy"/></figure>` : ''}
        <h1 class="book-h1">${esc(b.en)}</h1>
        <p class="book-te-title" lang="te">${b.te}</p>
        <p class="book-meta-line">${esc(b.meta)}</p>
        ${b.source ? `<a class="bn-source" href="${esc(b.source)}" target="_blank" rel="noopener">Stotra Nidhi — స్తోత్రనిధి ⇗</a>` : ''}
        ${b.chapters.length ? `<nav class="chapter-nav" data-slug="${b.slug}">
          ${b.chapters.map((c, i) => `<button class="chapter-btn${i === 0 ? ' active' : ''}" data-i="${i}">${esc(c.title)}</button>`).join('\n')}
        </nav>` : ''}
      </aside>
      <article class="reading-column">
        ${b.comingSoon
          ? `<div class="comingsoon-note">This book's text hasn't been added yet. Add chapters for it in <code>data.js</code>, or ask <b>Rushi</b> to search the internet for it.</div>`
          : b.chapters.map((c, i) =>
              `<div class="chapter-body" data-i="${i}"${i === 0 ? '' : ' style="display:none"'}>
                <h2 class="reading-h">${esc(c.title)}</h2>
                ${c.paras.map(p => `<p class="reading-p">${esc(p)}</p>`).join('\n')}
              </div>`).join('\n')}
      </article>
    </div>
  </section>`);
  parts.push(`</main>`);
  parts.push(fabAndShell(1));
  parts.push(`</div>`);
  return parts.join('\n');
}

/* helpers */
function deityBySlug(slug) { return D.deities.find(d => d.slug === slug); }
function bookBySlug(slug) { return D.books.find(b => b.slug === slug); }

/* write files */
function write(p, content) {
  fs.mkdirSync(path.dirname(path.join(ROOT, p)), { recursive: true });
  fs.writeFileSync(path.join(ROOT, p), content); console.log('wrote', p);
}

write('index.html', homePage());
write('audio.html', audioPage());
write('books.html', booksPage());
write('about.html', aboutPage());
write('temples.html', templesPage());
write('panchangam.html', panchangPage());
Object.keys(DEITY_PAGES).forEach(s => write('deity/' + s + '.html', deityPage(s)));
Object.keys(BOOK_PAGES).forEach(s => write('books/' + s + '.html', bookPage(s)));
TEMPLES.items.forEach(t => write('temples/' + t.id + '.html', templePage(t.id)));

console.log('Done. Generated 4 top-level pages + ' + Object.keys(DEITY_PAGES).length + ' deity pages + ' + Object.keys(BOOK_PAGES).length + ' book pages + 1 temples hub + ' + TEMPLES.items.length + ' temple pages.');