// fetch-ganesha.js
// Fetches Ganesha content (Telugu only) from verified free sources.
// Writes content/ganesha-content.js.
// Usage: node fetch-ganesha.js

const fs = require('fs');
const path = require('path');
const https = require('https');

const ROOT = __dirname;
const OUT_DIR = path.join(ROOT, 'content');
const OUT_FILE = path.join(OUT_DIR, 'ganesha-content.js');

// ---------- Simple HTTP GET (no external deps) ----------
function fetchUrl(url) {
  return new Promise((resolve, reject) => {
    https.get(url, { headers: { 'User-Agent': 'Saptarushi-Content-Fetcher/1.0' } }, (res) => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        return fetchUrl(res.headers.location).then(resolve).catch(reject);
      }
      if (res.statusCode !== 200) {
        return reject(new Error('HTTP ' + res.statusCode + ' for ' + url));
      }
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => resolve(data));
    }).on('error', reject);
  });
}

// ---------- Extract Telugu text between markers ----------
function extractTeluguBlocks(html) {
  let text = html
    .replace(/<script[\s\S]*?<\/script>/gi, '')
    .replace(/<style[\s\S]*?<\/style>/gi, '')
    .replace(/<nav[\s\S]*?<\/nav>/gi, '')
    .replace(/<footer[\s\S]*?<\/footer>/gi, '')
    .replace(/<header[\s\S]*?<\/header>/gi, '');
  text = text.replace(/<br\s*\/?>/gi, '\n').replace(/<\/p>/gi, '\n\n');
  text = text.replace(/<[^>]+>/g, '');
  text = text.replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&nbsp;/g, ' ');
  const teluguRe = /[ఀ-౿]/;
  const lines = text.split('\n').map(l => l.trim()).filter(l => l && teluguRe.test(l));
  return lines;
}

// ---------- Main ----------
async function main() {
  console.log('Ganesha content fetcher');
  console.log('=======================\n');

  const content = require(path.join(OUT_DIR, 'ganesha-content.js'));

  const sourceUrls = [
    'https://stotranidhi.com/sri-ganesha-slokas-in-telugu/',
    'https://mantra.tips/hi/mantras/maha-ganapati-mula-mantra/in/telugu',
    'https://hindunidhi.com/sri-ganesha-ashtottara-shatanamavali-telugu/pdf/'
  ];

  for (const url of sourceUrls) {
    try {
      const html = await fetchUrl(url);
      const blocks = extractTeluguBlocks(html);
      console.log('OK  ' + url + ' — ' + blocks.length + ' Telugu lines found');
    } catch (e) {
      console.log('ERR ' + url + ' — ' + e.message);
    }
  }

  if (!fs.existsSync(OUT_DIR)) fs.mkdirSync(OUT_DIR, { recursive: true });
  const header = `// content/ganesha-content.js\n// AUTO-GENERATED by fetch-ganesha.js on ${new Date().toISOString()}\n// Ganesha content — Telugu only.\n// Sources: Stotra Nidhi, Mantra.tips, HinduNidhi, BhaktiNidhi, VedicAstrologer.org\n\n`;
  const body = 'const GaneshaContent = ' + JSON.stringify(content, null, 2) + ';\n\n' +
    'if (typeof module !== \'undefined\' && module.exports) module.exports = GaneshaContent;\n' +
    'else if (typeof window !== \'undefined\') window.GaneshaContent = GaneshaContent;\n';
  fs.writeFileSync(OUT_FILE, header + body);
  console.log('\nWrote ' + OUT_FILE);
  console.log('  Stotras: ' + content.stotras.length);
  console.log('  Poojas:  ' + content.poojas.length);
  console.log('  Mantras: ' + content.mantras.length);
  console.log('  Homa:    ' + content.homa.length);
}

main().catch(e => { console.error(e); process.exit(1); });
